# Common Google Place types used for LLM classification (v1 subset)
GOOGLE_PLACE_TYPES = [
    "restaurant",
    "cafe",
    "bar",
    "bakery",
    "meal_takeaway",
    "supermarket",
    "grocery_or_supermarket",
    "convenience_store",
    "department_store",
    "clothing_store",
    "book_store",
    "pharmacy",
    "hospital",
    "doctor",
    "dentist",
    "pharmacy",
    "school",
    "university",
    "library",
    "park",
    "tourist_attraction",
    "museum",
    "church",
    "synagogue",
    "mosque",
    "hindu_temple",
    "gas_station",
    "parking",
    "bus_station",
    "subway_station",
    "train_station",
    "airport",
    "lodging",
    "hotel",
    "gym",
    "bank",
    "atm",
    "post_office",
    "police",
    "fire_station",
    "city_hall",
    "courthouse",
    "embassy",
    "local_government_office",
    "store",
    "shopping_mall",
    "point_of_interest",
    "establishment",
]

# Primary types we prefer as top-level predictions
PRIMARY_TYPES = {
    "restaurant",
    "cafe",
    "bar",
    "bakery",
    "supermarket",
    "grocery_or_supermarket",
    "convenience_store",
    "hospital",
    "doctor",
    "school",
    "university",
    "library",
    "park",
    "museum",
    "parking",
    "gas_station",
    "lodging",
    "hotel",
    "bank",
    "pharmacy",
    "store",
    "shopping_mall",
    "church",
    "train_station",
    "bus_station",
    "subway_station",
    "airport",
}

OSM_TO_GOOGLE_HINTS = {
    "restaurant": "restaurant",
    "cafe": "cafe",
    "fast_food": "restaurant",
    "bar": "bar",
    "pub": "bar",
    "hospital": "hospital",
    "clinic": "doctor",
    "doctors": "doctor",
    "pharmacy": "pharmacy",
    "school": "school",
    "kindergarten": "school",
    "college": "university",
    "university": "university",
    "library": "library",
    "park": "park",
    "playground": "park",
    "parking": "parking",
    "supermarket": "supermarket",
    "convenience": "convenience_store",
    "mall": "shopping_mall",
    "shop": "store",
}
